# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/mmofu"

[social.params]
icon = "brand-github"

[[social]]
identifier = "X"
name = "X"
url = "https://x.com/mofummmmofu"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "bluesky"
name = "Bluesky"
url = "https://bsky.app/profile/mmofu.bsky.social"

[social.params]
icon = "link"